/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Praktikum_19_06_2025;

/**
 *
 * @author acer
 */
public class DrinkMenu extends javax.swing.JFrame {

    /**
     * Creates new form DrinkMenu
     */
    private MainMenu main;
    
    public DrinkMenu() {
        initComponents();
    }
    
    public DrinkMenu(MainMenu main){
        this.main = main;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        checkMojito = new javax.swing.JCheckBox();
        textMojito = new javax.swing.JTextField();
        comboMojito = new javax.swing.JComboBox<>();
        textTotalMojito = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textTotalAll = new javax.swing.JTextField();
        doneButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        checkPepsi = new javax.swing.JCheckBox();
        textPepsi = new javax.swing.JTextField();
        comboPepsi = new javax.swing.JComboBox<>();
        textTotalPepsi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Drinks");

        checkMojito.setText("Mojito");
        checkMojito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMojitoActionPerformed(evt);
            }
        });

        comboMojito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quantity", "1", "2", "3", "4" }));
        comboMojito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMojitoActionPerformed(evt);
            }
        });

        textTotalMojito.setText("0");
        textTotalMojito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTotalMojitoActionPerformed(evt);
            }
        });

        jLabel2.setText("Total");

        textTotalAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTotalAllActionPerformed(evt);
            }
        });

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        returnButton.setText("Back");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");

        checkPepsi.setText("Pepsi");
        checkPepsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPepsiActionPerformed(evt);
            }
        });

        comboPepsi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quantity", "1", "2", "3", "4" }));
        comboPepsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPepsiActionPerformed(evt);
            }
        });

        textTotalPepsi.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resetButton)
                        .addGap(18, 18, 18)
                        .addComponent(returnButton)
                        .addGap(18, 18, 18)
                        .addComponent(doneButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(checkMojito)
                                .addComponent(checkPepsi))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textMojito)
                                .addComponent(textPepsi, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(comboMojito, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboPepsi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textTotalMojito)
                                .addComponent(textTotalPepsi, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(textTotalAll, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkMojito)
                    .addComponent(textMojito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMojito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTotalMojito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(textTotalAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkPepsi)
                    .addComponent(textPepsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPepsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTotalPepsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doneButton)
                    .addComponent(returnButton)
                    .addComponent(resetButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textTotalAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTotalAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTotalAllActionPerformed

    private void checkMojitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMojitoActionPerformed
        textMojito.setText("70000");
    }//GEN-LAST:event_checkMojitoActionPerformed

    private void comboMojitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMojitoActionPerformed
        int sum = (int) comboMojito.getSelectedIndex();
        double price = Double.parseDouble(textMojito.getText());
        double total = sum * price;
        textTotalMojito.setText(Double.toString(total));
    }//GEN-LAST:event_comboMojitoActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        double mojito = Double.parseDouble(textTotalMojito.getText());
        double pepsi = Double.parseDouble(textTotalPepsi.getText());
        double total = mojito + pepsi;
        textTotalAll.setText(Double.toString(total));
    }//GEN-LAST:event_doneButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        String total = textTotalAll.getText();
        main.setTotalDrink(total);
        this.dispose();
    }//GEN-LAST:event_returnButtonActionPerformed

    private void comboPepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPepsiActionPerformed
        int sum = (int) comboPepsi.getSelectedIndex();
        double price = Double.parseDouble(textPepsi.getText());
        double total = sum * price;
        textTotalPepsi.setText(Double.toString(total));
    }//GEN-LAST:event_comboPepsiActionPerformed

    private void checkPepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPepsiActionPerformed
        textPepsi.setText("15000");
    }//GEN-LAST:event_checkPepsiActionPerformed

    private void textTotalMojitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTotalMojitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTotalMojitoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrinkMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrinkMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrinkMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrinkMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrinkMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkMojito;
    private javax.swing.JCheckBox checkPepsi;
    private javax.swing.JComboBox<String> comboMojito;
    private javax.swing.JComboBox<String> comboPepsi;
    private javax.swing.JButton doneButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton returnButton;
    private javax.swing.JTextField textMojito;
    private javax.swing.JTextField textPepsi;
    private javax.swing.JTextField textTotalAll;
    private javax.swing.JTextField textTotalMojito;
    private javax.swing.JTextField textTotalPepsi;
    // End of variables declaration//GEN-END:variables
}
