/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Praktikum_05_06_2025;

import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class StorePayment extends javax.swing.JFrame {

    /**
     * Creates new form StorePayment
     */
    public StorePayment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labTitle = new javax.swing.JLabel();
        labItem = new javax.swing.JLabel();
        labSum = new javax.swing.JLabel();
        labTotal = new javax.swing.JLabel();
        labPrice = new javax.swing.JLabel();
        combItemName = new javax.swing.JComboBox<>();
        editSum = new javax.swing.JTextField();
        editTotal = new javax.swing.JTextField();
        editPrice = new javax.swing.JTextField();
        buttonSubmit = new javax.swing.JButton();
        labDiscount = new javax.swing.JLabel();
        editDiscount = new javax.swing.JTextField();
        labPay = new javax.swing.JLabel();
        editPay = new javax.swing.JTextField();
        labReturn = new javax.swing.JLabel();
        editReturn = new javax.swing.JTextField();
        buttonReturn = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labTitle.setText("Store Payment");

        labItem.setText("Item");

        labSum.setText("Sum");

        labTotal.setText("Total");

        labPrice.setText("Price");

        combItemName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Item", "Intel i9 14900K", "Intel i5 13250U", "Intel i7 12050H", "AMD Ryzen 3 3000 Series", "AMD Ryzen 7 7000 Series" }));
        combItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combItemNameActionPerformed(evt);
            }
        });

        buttonSubmit.setForeground(new java.awt.Color(0, 255, 51));
        buttonSubmit.setText("Done");
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });

        labDiscount.setText("Discount");

        labPay.setText("Pay");

        labReturn.setText("Return");

        buttonReturn.setText("Return");
        buttonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReturnActionPerformed(evt);
            }
        });

        buttonReset.setText("Reset");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        buttonExit.setForeground(new java.awt.Color(255, 0, 0));
        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labTitle)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labItem)
                            .addComponent(labSum)
                            .addComponent(labTotal)
                            .addComponent(labDiscount)
                            .addComponent(labPay)
                            .addComponent(labReturn))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(editTotal)
                                .addComponent(editSum, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(combItemName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(editDiscount)
                                .addComponent(editPay))
                            .addComponent(editReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labPrice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonReturn)
                                    .addComponent(buttonSubmit)
                                    .addComponent(buttonReset)
                                    .addComponent(buttonExit))
                                .addGap(64, 64, 64))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labItem)
                    .addComponent(labPrice)
                    .addComponent(combItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labSum)
                            .addComponent(editSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labTotal)
                            .addComponent(editTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labDiscount)
                            .addComponent(editDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labPay)
                            .addComponent(editPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labReturn)
                            .addComponent(editReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonSubmit)
                        .addGap(18, 18, 18)
                        .addComponent(buttonReturn)
                        .addGap(18, 18, 18)
                        .addComponent(buttonReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonExit)
                        .addGap(1, 1, 1)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        int opt = JOptionPane.showConfirmDialog(this, "..., I'm Gay", "Warning", JOptionPane.YES_NO_OPTION);
        if(opt == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_buttonExitActionPerformed

    private void combItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combItemNameActionPerformed
        int itemName = (int) combItemName.getSelectedIndex();
        
        switch(itemName){
            case 1:
                editPrice.setText("9000"); break;
            case 2:
                editPrice.setText("2500"); break;
            case 3:
                editPrice.setText("5000"); break;
            case 4:
                editPrice.setText("4000"); break;
            case 5:
                editPrice.setText("7000"); break;
        }
    }//GEN-LAST:event_combItemNameActionPerformed

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        int price = Integer.parseInt(editPrice.getText());
        int sum = Integer.parseInt(editSum.getText());
        int total = price * sum;
        editTotal.setText(Integer.toString(total));
        double discount = 0;
        
        if(total > 50000){
            discount = 0.1 * total;
        }
        
        double payment = total - discount;
        editDiscount.setText(Double.toString(discount));
        editTotal.setText(Double.toString(payment));
    }//GEN-LAST:event_buttonSubmitActionPerformed

    private void buttonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReturnActionPerformed
        double cash = Double.parseDouble(editPay.getText());
        double total = Double.parseDouble(editTotal.getText());
        double refund = 0;
        
        if(cash < total){
            JOptionPane.showMessageDialog(this, "Insufficient Fund", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            refund = cash - total;
            editReturn.setText(Double.toString(refund));
        }
    }//GEN-LAST:event_buttonReturnActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        editPrice.setText("");
        editSum.setText("");
        editTotal.setText("");
        editDiscount.setText("");
        editPay.setText("");
        editReturn.setText("");
        combItemName.setSelectedIndex(0);
    }//GEN-LAST:event_buttonResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StorePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StorePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StorePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StorePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StorePayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonReset;
    private javax.swing.JButton buttonReturn;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JComboBox<String> combItemName;
    private javax.swing.JTextField editDiscount;
    private javax.swing.JTextField editPay;
    private javax.swing.JTextField editPrice;
    private javax.swing.JTextField editReturn;
    private javax.swing.JTextField editSum;
    private javax.swing.JTextField editTotal;
    private javax.swing.JLabel labDiscount;
    private javax.swing.JLabel labItem;
    private javax.swing.JLabel labPay;
    private javax.swing.JLabel labPrice;
    private javax.swing.JLabel labReturn;
    private javax.swing.JLabel labSum;
    private javax.swing.JLabel labTitle;
    private javax.swing.JLabel labTotal;
    // End of variables declaration//GEN-END:variables
}
